### PR TITLE
add NOTICE and CONTRIBUTING files

### PR DESCRIPTION
**Pull request by lukasj**
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

### CODE REVIEW

**Comment by keilw** [comment]
@lukasj I guess you can merge it yourself. If you need review from a PMC member here, too, then @m0mus may have to approve it as well.

**Comment by lukasj** [comment]
this is exactly that kind of thing which I'd rather get reviewed by at-least on PMC ;-)

**Comment by keilw** [comment]
I also assigned @m0mus as reviewer. Having committers approve it, too cannot hurt. I guess the Eclipse mechanism cannot implement something like checking who is in the PMC and who isn't but wait for both reviews to take place ;-)

**Comment by lukasj** [comment]
@waynebeaton is the one who asked for this, so he should be the best person to double check this is correct - it's copy&paste but anyway - check twice, commit once :-)
I wanted to avoid spamming especially those who are already aware of this from the very beginning.

**Comment by lukasj** [comment]
@keilw see https://bugs.eclipse.org/bugs/show_bug.cgi?id=535087 for details

**Pull request merged**
