### PR TITLE
Issue #292 - update JsonParserImpl and reject duplicate keys unit test

### PR DESCRIPTION
**Pull request by JohnTimm**
Signed-off-by: John T.E. Timm <johntimm@us.ibm.com>

### CODE REVIEW

**Comment by JohnTimm** [comment]
The Travis CI build log contains the following error:
```
ERROR] Failed to execute goal on project jakarta.json-tck-tests: Could not resolve dependencies for project org.eclipse.jsonp:jakarta.json-tck-tests:jar:1.0.0-SNAPSHOT: Could not find artifact org.eclipse.jsonp:jakarta.json:jar:2.0.1-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) 
```
Not sure why it wouldn't be resolving the artifact properly but I don't think it has to do with my changes. @lukasj FYI

**Review by lukasj — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
there is something wrong with the setup of those TCKs, it's likely that changing package to install would help. Weld update is required to support running on JDK 16+, so unless someone jumps in and fixes it, I'll do that after the implementation moves out from this repo (should happen soon)

**Comment by JohnTimm** [comment]
> there is something wrong with the setup of those TCKs, it's likely that changing package to install would help. Weld update is required to support running on JDK 16+ in tcks as well, so unless someone jumps in and fixes it, I'll do that all at once after the implementation moves out from this repo (should happen soon)

@lukasj when is the next patch release that will include this fix? Is it possible to tag a 2.0.2 before you leave this repo?

**Comment by lukasj** [comment]
no patch release is planned. This change is part of parsson - see https://github.com/eclipse-ee4j/parsson/releases/tag/1.0.0

**Pull request merged**
