### PR TITLE
Fixed documentation error for Operation.REPLACE.

### PR DESCRIPTION
**Pull request by jesperdj**
The documentation for JsonPatch.Operation.REPLACE said: "remove" operation. This must be: "replace" operation.
Looks like a copy-and-paste error from the REMOVE operation.

### CODE REVIEW

**Comment by leadpony** [comment]
Hello @jesperdj 

Today, Travis CI build always fails for `openjdk11` target in any projects.

**Comment by keilw** [comment]
@jesperdj It seems your ECA is not in place yet, have you looked into signing or re-signing it?

**Comment by jesperdj** [comment]
> @jesperdj It seems your ECA is not in place yet, have you looked into signing or re-signing it?

Hi keilw, I did sign the ECA: https://accounts.eclipse.org/users/jdejong2wg/eca

**Comment by keilw** [comment]
@jesperdj you don't seem to have an ECA, is that correct?

**Comment by jesperdj** [comment]
@keilw No that is not correct? Did you see my link?
https://accounts.eclipse.org/users/jdejong2wg/eca
Is there something wrong with it, or can you not relate my GitHub account to my ECA? What can I do to fix this?

**Comment by keilw** [comment]
@jesperdj Plese ask Eclipse EMO to help you with that, @waynebeaton may be able to assist you or point you to a colleague, it is not possible to merge before that.

**Comment by lukasj** [comment]
commit is missing sign-off, that means it is missing what you get after using 'git commit -s' or 'git commit -amend -s' or by adding a "Signed-off-by: some name &lt;someone@somewhere.com&gt;" footer to the commit message

**Comment by jesperdj** [comment]
@lukasj Thanks, I've amended the commit and added my name and e-mail address.

**Comment by lukasj** [comment]
"There is a valid ECA on file for ...@gmail.com." says ECA validation tool, so this is fine from legal point of view

**Comment by m0mus** [comment]
ECA looks fine. Merging.

**Pull request merged**
