### PR TITLE
rename TCK package from package jakarta.jsonp.tck to jsonp.tck

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Copyright dates need to be updated and locally, I always see a test failure (with and without changes):
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ClientTests.jsonParserCurrentEvent:1862 NoSuchMethod 'jakarta.json.stream.Json...
[ERROR]   ClientTests.testDuplicateKeysFirst:3214 NoClassDefFound jakarta/json/JsonConfi...
[ERROR]   ClientTests.testDuplicateKeysLast:3233 NoClassDefFound jakarta/json/JsonConfig...
[ERROR]   ClientTests.testDuplicateKeysNone:3194 NoClassDefFound jakarta/json/JsonConfig...
[ERROR]   ClientTests.jsonNumber21Test:347 NoSuchMethod 'jakarta.json.JsonNumber jakarta...
[INFO] 
[ERROR] Tests run: 177, Failures: 0, Errors: 5, Skipped: 0
```

### CODE REVIEW

**Comment by lukasj** [comment]
rebasing on master should help

**Comment by lukasj** [comment]
wrt copyright updates, I run (on mac):

```
$ git add
$ for f in $(git diff --cached --name-only); do sed -E -i '' -e "s/([[:digit:]][[:digit:]][[:digit:]][[:digit:]]), ([[:digit:]][[:digit:]][[:digit:]][[:digit:]])/\1, 2022/" $f; done
```

eventually also an alternative for files created in 2021

**Comment by scottmarlow** [comment]
> rebasing on master should help

Thanks, ^ addressed most of the failures, I'm seeing the below failure now with my changes:

```
[ERROR] jsonp.tck.pluggability.jsonprovidertests.ClientTests.jsonProviderTest1  Time elapsed: 0.045 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: jsonProviderTest1 Failed ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
        at jsonp.tck.pluggability.jsonprovidertests.ClientTests.jsonProviderTest1(ClientTests.java:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
.
.
.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientTests.jsonProviderTest1:105 jsonProviderTest1 Failed ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0
```

I don't get the ^ failure if I switch to the `master` branch, build the TCK and test again.  

From `impl-tck/tck-tests-pluggability/target/surefire-reports/TEST-jsonp.tck.pluggability.jsonprovidertests.ClientTests.xml`output logged after the test:
```
Jan 12, 2022 10:27:44 AM jsonp.tck.pluggability.jsonprovidertests.ClientTests jsonProviderTest1
INFO: provider class=jsonp.tck.provider.MyJsonProvider
Jan 12, 2022 10:27:44 AM jsonp.tck.pluggability.jsonprovidertests.ClientTests jsonProviderTest1
WARNING: Current provider is not my provider - unexpected.
Jan 12, 2022 10:27:44 AM jsonp.tck.pluggability.jsonprovidertests.ClientTests jsonProviderTest1
INFO: Providers: [jsonp.tck.provider.MyJsonProvider@7180e701, org.eclipse.parsson.JsonProviderImpl@4e2c95ee]
```

**Comment by scottmarlow** [comment]
I updated the information logged to show:
```
LOGGER.warning("Current provider is not my provider - unexpected.  providerClass=" + providerClass + " , MY_JSONPROVIDER_CLASS=" +MY_JSONPROVIDER_CLASS);
```
^ shows:
```
LOGGER.warning("Current provider is not my provider - unexpected.  providerClass=" + providerClass + " , MY_JSONPROVIDER_CLASS=" +MY_JSONPROVIDER_CLASS);
```

**Comment by scottmarlow** [comment]
I'm trying to run on master branch with latest changes locally and seeing failure:
```
Failures: 
[ERROR]   JsonProviderTest.systemProperty:57 expected: <jakarta.jsonp.tck.api.provider.JsonProviderTest.DummyJsonProvider> but was: <org.eclipse.parsson.JsonProviderImpl>
```

**Comment by lukasj** [comment]
what exactly are you trying to run? just rebase, build the tck, unzip the binary and run `bin/pom.xml` - the force will guide you (or user guide? who knows ;-) ); ignore the impl-tck folder

**Comment by scottmarlow** [comment]
Replaced by https://github.com/eclipse-ee4j/jsonp/pull/355

**Comment by scottmarlow** [comment]
> what exactly are you trying to run? just rebase, build the tck, unzip the binary and run bin/pom.xml - the force will guide you (or user guide? who knows ;-) ); ignore the impl-tck folder

I had done something like:
> cd api;mvn clean install;cd ../tck;mvn clean install;cd ../impl-tck;mvn clean install

Thanks, I will ignore the impl-tck folder

**Pull request closed without merging**
