### PR TITLE
Move the implementation to a different groupId and package namespace

### PR DESCRIPTION
**Pull request by lukasj**
this is to allow co-existence of the old (javax based) implementation together with the new (jakarta based) one in the same VM.

In general:
* Implementation package name changes from `org.glassfish.json` to `org.eclipse.jsonp`
* project's groupId changes from `org.glassfish` to `org.eclipse.jsonp`
* module name changes from `org.glassfish.jakarta.json` to `org.eclipse.jsonp`

### CODE REVIEW

**Comment by keilw** [comment]
@lukasj Happy to review that after the Spec MR1 later today.

**Comment by lukasj** [comment]
I do plan one or two possibly breaking changes related to packaging (basically switch "module" artifact with the "legacy" one) but I'll create another PR(s) for that as I prefer to keep this as "rename-only"

**Comment by jjspiegel** [comment]
Thank you @lukasj !

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
