### PR TITLE
2.0.1 release (implementation)

### PR DESCRIPTION
**Pull request by lukasj**

### CODE REVIEW

**Comment by keilw** [comment]
Does this correspond to https://github.com/jakartaee/specifications/pull/343?

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by lukasj** [comment]
@keilw no, this is implementation only

**Comment by keilw** [comment]
I know but is it the matching implementation, judging by the number it should?

**Comment by keilw** [comment]
I guess every committer can merge it, but as @m0mus approved, will you merge it @lukasj, or should I?

**Pull request merged**
