### PR TITLE
Cache JsonProvider.provider() result as per javadoc recommendation

### PR DESCRIPTION
**Pull request by gbloisi**
I got through this because I found a performance hostpot in calling Json methods (about 500 microsec per call on a i5)

### CODE REVIEW

**Comment by gbloisi** [comment]
Is there a common pattern to cache singleton instances with classloader specific implementations? I may lookup at some examples and adapt for this case. Thanks

**Comment by lukasj** [comment]
you may want to look at Issue #26 . The javadoc is targeted to _users_ of the API, not to the API itself

**Comment by cwhite102** [comment]
Is this fix going anywhere soon?  
I believe this bug is why calls to Json.createValue() are a huge performance issue.  (each create value call is >100us)

**Comment by JohnTimm** [comment]
> you may want to look at Issue #26 . The javadoc is targeted to _users_ of the API, not to the API itself

@lukasj 
This is not a sufficient solution when the internal implementation calls Json.createXXX methods that in turn calls JsonProvider.provider(). What about a solution that a) allows clients to set the provider used by the javax.json.Json class and b) does it on a per context class loader basis to support container environments with multiple class loaders? I put together a "straw man" here:

https://github.com/eclipse-ee4j/jsonp/issues/205#issuecomment-519973697

**Pull request closed without merging**
