### PR TITLE
tck ug fixes,

### PR DESCRIPTION
**Pull request by lukasj**
correct CI,
tool versions,
removal of deployment requirements,
removal of duplicities,
UG updates,
added `bin/pom.xml` to simplify test execution 

Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>

### CODE REVIEW

**Review by gurunrao — COMMENTED** [review]
PR LGTM, https://github.com/eclipse-ee4j/jsonp/blob/915ad60681b6762593433ff4e6d5ebc433d5ba41/tck/tck-docs/userguide/src/main/jbake/content/attributes.conf doesn't have copyright, should we add one?

**Comment by gurunrao** [comment]
> PR LGTM, https://github.com/eclipse-ee4j/jsonp/blob/915ad60681b6762593433ff4e6d5ebc433d5ba41/tck/tck-docs/userguide/src/main/jbake/content/attributes.conf doesn't have copyright, should we add one?

looks like we don't support copyright for conf file.

**Review by gurunrao — APPROVED** [review]

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by jansupol** [comment]
tck/tck-docs/userguide/src/main/jbake/templates/footer.ftl could have had a copyright header....

**Pull request merged**
